{
  "language": "android",
  "android": {
    "components": [
      "tools",
      "build-tools-23.0.3",
      "android-23",
      "extra"
    ]
  },
  "script": [
    "./gradlew build jacocoTestReport"
  ],
  "after_success": [
    "bash <(curl -s https://codecov.io/bash)"
  ],
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
